# Site settings
title: Convex Solid Voids
email: joao.neves@edu.ulisboa.pt
description: >-
  Convex and Solid-Voids is a research project developed by the Design
  Computing Group at the Faculty of Architecture, University of Lisbon.
baseurl: "/csv_public"
url: "https://dcg-lx.github.io"
twitter_username: ponceleao
github_username: joaoponceleao

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
